### PR TITLE
fixed issue with coordinates were cleared

### PR DESCRIPTION
**Pull request by matsudamper**
Occurs issue #21 in a project uses Compose Foundation1.2.

### CODE REVIEW

**Comment by mxalbert1996** [comment]
I'd like to add a comment in the code. Please check "Allow edits from maintainers" so that I can push the commit.

**Comment by matsudamper** [comment]
Is this?

**Comment by matsudamper** [comment]
It's a little different.


https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by matsudamper** [comment]
Can you edit?

**Comment by mxalbert1996** [comment]
You forked the repo from Tlaster/Zoomable instead of mine so I don't have the permission to push to your repo.
Merged in #23.

**Pull request closed without merging**
